---
abstract: 'a POE based RADIUS server component'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-RADIUS
requires:
  Math::Random: 0.69
  Net::IP::Minimal: 0.02
  Net::Radius::Dictionary: 1.55
  Net::Radius::Packet: 1.55
  POE: 0.9999
  POE::Component::Client::RADIUS: 1
  perl: 5.006
resources:
  homepage: https://github.com/bingos/poe-component-server-radius
  repository: https://github.com/bingos/poe-component-server-radius.git
version: 1.08
